In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

/var/folders/2r/434wj8v51w31pb2v3vm0vphm0000gn/T/ipykernel_7658/3828565490.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import TextLoader

In [2]:
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5688,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5689,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5690,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5691,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...
5692,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0,'I'm Telling You Stories': Jeanette Winterson ...,9789042003408 This is a jubilant and rewarding...

In [5]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

In [6]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0.1, chunk_overlap=0, separator="\n")
# chunk_size = 0.1 -- if this is more than one it may split on a chunk size rather than the separator
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 373, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 482, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 211, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 513, which is longer than the specified 0
Created a chunk of size 752, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 728, which is longer than the specified 0
Created a chunk of size 721, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 473, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 681, which is longer than the specified 0
Created a chunk of size 153, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 553, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 787, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 533, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 563, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 410, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 595, which is longer than the specified 0
Created a chunk of size 476, which is longer than the specified 0
Created a chunk of size 459, which is longer than the specified 0
Created a chunk of size 128, which is longer than the specified 0
Created a chunk of size 257, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 614, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 887, which is longer than the specified 0
Created a chunk of size 693, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 146, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 479, which is longer than the specified 0
Created a chunk of size 300, which is longer than the specified 0
Created a chunk of size 520, which is longer than the specified 0
Created a chunk of size 647, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 686, which is longer than the specified 0
Created a chunk of size 548, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 126, which is longer than the specified 0
Created a chunk of size 406, which is longer than the specified 0
Created a chunk of size 1184, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 1057, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 417, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 526, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 899, which is longer than the specified 0
Created a chunk of size 1270, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 1635, which is longer than the specified 0
Created a chunk of size 436, which is longer than the specified 0
Created a chunk of size 249, which is longer than the specified 0
Created a chunk of size 777, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 514, which is longer than the specified 0
Created a chunk of size 958, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 133, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 851, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1119, which is longer than the specified 0
Created a chunk of size 836, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 235, which is longer than the specified 0
Created a chunk of size 732, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 773, which is longer than the specified 0
Created a chunk of size 278, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 445, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 912, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 844, which is longer than the specified 0
Created a chunk of size 1126, which is longer than the specified 0
Created a chunk of size 1073, which is longer than the specified 0
Created a chunk of size 1318, which is longer than the specified 0
Created a chunk of size 361, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 139, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 130, which is longer than the specified 0
Created a chunk of size 240, which is longer than the specified 0
Created a chunk of size 171, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1141, which is longer than the specified 0
Created a chunk of size 1004, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 954, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 639, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 793, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 254, which is longer than the specified 0
Created a chunk of size 1422, which is longer than the specified 0
Created a chunk of size 1083, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 806, which is longer than the specified 0
Created a chunk of size 1812, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1180, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 1642, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 1930, which is longer than the specified 0
Created a chunk of size 872, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 577, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1142, which is longer than the specified 0
Created a chunk of size 557, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 221, which is longer than the specified 0
Created a chunk of size 1135, which is longer than the specified 0
Created a chunk of size 722, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 765, which is longer than the specified 0
Created a chunk of size 606, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 857, which is longer than the specified 0
Created a chunk of size 1032, which is longer than the specified 0
Created a chunk of size 189, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 495, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 348, which is longer than the specified 0
Created a chunk of size 733, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 1015, which is longer than the specified 0
Created a chunk of size 970, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 544, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 207, which is longer than the specified 0
Created a chunk of size 376, which is longer than the specified 0
Created a chunk of size 931, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 854, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 324, which is longer than the specified 0
Created a chunk of size 241, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 704, which is longer than the specified 0
Created a chunk of size 1912, which is longer than the specified 0
Created a chunk of size 395, which is longer than the specified 0
Created a chunk of size 485, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 556, which is longer than the specified 0
Created a chunk of size 386, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 425, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 166, which is longer than the specified 0
Created a chunk of size 624, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 994, which is longer than the specified 0
Created a chunk of size 847, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 336, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2030, which is longer than the specified 0
Created a chunk of size 396, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 698, which is longer than the specified 0
Created a chunk of size 822, which is longer than the specified 0
Created a chunk of size 354, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 195, which is longer than the specified 0
Created a chunk of size 508, which is longer than the specified 0
Created a chunk of size 663, which is longer than the specified 0
Created a chunk of size 1282, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1056, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 269, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 225, which is longer than the specified 0
Created a chunk of size 222, which is longer than the specified 0
Created a chunk of size 160, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 969, which is longer than the specified 0
Created a chunk of size 613, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 289, which is longer than the specified 0
Created a chunk of size 146, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 963, which is longer than the specified 0
Created a chunk of size 232, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0

In [7]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [8]:
db_books = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings())

In [9]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 3)
docs

[Document(id='55cfca95-a93e-4e1f-8cf9-3c81757be179', metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='0eb5d636-84eb-4e0a-b1fe-338633b84828', metadata={'source': 'tagged_description.txt'}, page_content='9780761316800 A child observes the coming of winter and its effects on the weather, animals, and plants. Includes suggestions for wintertime activities.'),
 Document(id='896e0702-c34f-4a78-a6be-7f5f122473b2', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects.")]

In [10]:
# get the full data of the top book from the query
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
4113,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [14]:
def get_semantic_recommendation(query: str) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 30)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [12]:
get_semantic_recommendation("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
31,9780006754893,0006754899,A Small Pinch of Weather,Joan Aiken,"Children's stories, English",http://books.google.com/books/content?id=QiFhO...,A magical and fantastic collection of early st...,2000.0,4.27,239.0,116.0,A Small Pinch of Weather: And Other Stories,9780006754893 A magical and fantastic collecti...
107,9780060192501,006019250X,The Illustrated Alchemist,Paulo Coelho;Alan R. Clarke;Moebius,Fiction,http://books.google.com/books/content?id=1YX2u...,This fable aims teaches the reader to open the...,1998.0,3.85,198.0,236.0,The Illustrated Alchemist: A Fable About Follo...,9780060192501 This fable aims teaches the read...
290,9780060915414,0060915412,Teaching a Stone to Talk,Annie Dillard,Literary Criticism,http://books.google.com/books/content?id=pY5ll...,"Here, in this compelling assembly of writings,...",1988.0,4.20,177.0,4046.0,Teaching a Stone to Talk: Expeditions and Enco...,"9780060915414 Here, in this compelling assembl..."
449,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
462,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
651,9780140283334,0140283331,Lord of the Flies,William Golding,Fiction,NaN,The classic study of human nature which depict...,1999.0,3.67,182.0,1861140.0,Lord of the Flies,9780140283334 The classic study of human natur...
728,9780140448009,0140448004,Three Tales,Gustave Flaubert;Roger Whitehouse;Geoffrey Wall,Fiction,http://books.google.com/books/content?id=XFzga...,Features short fiction by the French naturalis...,2005.0,3.71,110.0,3050.0,Three Tales,9780140448009 Features short fiction by the Fr...
745,9780140568196,0140568190,The Giraffe and the Pelly and Me,Roald Dahl;Quentin Blake,Candy,http://books.google.com/books/content?id=J7FdI...,"A Dahl story in which the giraffe, the pelican...",2001.0,3.81,32.0,16265.0,The Giraffe and the Pelly and Me,9780140568196 A Dahl story in which the giraff...
749,9780140621624,0140621628,The Railway Children,E. Nesbit,Fiction,http://books.google.com/books/content?id=fFesd...,"When their father is sent away to prison, thre...",1995.0,4.00,212.0,178.0,The Railway Children,9780140621624 When their father is sent away t...
1151,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,340101.0,The Very Hungry Caterpillar,9780241003008 Eric Carle's children's classic ...
1748,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
1861,9780375802430,0375802436,Flap Your Wings,NaN,Juvenile Fiction,http://books.google.com/books/content?id=yK46l...,"Two birds unwittingly hatch an alligator egg, ...",2000.0,4.24,48.0,1228.0,Flap Your Wings,9780375802430 Two birds unwittingly hatch an a...
1955,9780385334303,0385334303,The Naked Ape,Desmond Morris,Science,http://books.google.com/books/content?id=CS-GP...,"Examines sex, child rearing, fighing, feeding ...",1999.0,3.95,256.0,6479.0,The Naked Ape: A Zoologist's Study of the Huma...,"9780385334303 Examines sex, child rearing, fig..."
2043,9780393061062,039306106X,Will Eisner's New York,Will Eisner,Comics & Graphic Novels,http://books.google.com/books/content?id=RdOf4...,A quartet of graphic works explores the lives ...,2006.0,4.36,421.0,1242.0,Will Eisner's New York: Life in the Big City,9780393061062 A quartet of graphic works explo...
2053,9780393311396,0393311392,Eight Little Piggies,Stephen Jay Gould,Nature,http://books.google.com/books/content?id=_kOoV...,In the sixth volume of essays from Natural His...,1994.0,4.09,480.0,699.0,Eight Little Piggies: Reflections in Natural H...,9780393311396 In the sixth volume of essays fr...
2056,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in...,William Cronon,Law,http://books.google.com/books/content?id=w04mj...,"Essays by revisionist historians, scientists, ...",1996.0,4.16,560.0,649.0,Uncommon Ground: Rethinking the Human Place in...,9780393315110 Essays by revisionist historians...
2122,9780394820378,0394820371,The Phantom Tollbooth,Norton Juster,Juvenile Fiction,http://books.google.com/books/content?id=6bPVD...,A journey through a land where Milo learns the...,1996.0,4.21,256.0,206193.0,The Phantom Tollbooth,9780394820378 A journey through a land where M...
2301,9780439551892,0439551897,Catwings,Ursula K. Le Guin,Juvenile Fiction,http://books.google.com/books/content?id=L2wXJ...,Four young cats with wings leave the city slum...,2003.0,4.08,40.0,6304.0,Catwings: A Catwings Tale,9780439551892 Four young cats with wings leave...
2383,9780440362050,0440362059,My Name is Aram,William Saroyan,Fiction,http://books.google.com/books/content?id=2P3XA...,A small boy finds excitement and promise in th...,1966.0,4.15,151.0,975.0,My Name is Aram,9780440362050 A small boy finds excitement and...
3056,9780571090242,0571090249,Death of a Naturalist,Seamus Heaney,Poetry,http://books.google.com/books/content?id=et6dA...,Death of a Naturalist marks the auspicious out...,1969.0,4.29,57.0,63.0,Death of a Naturalist: Volume one,9780571090242 Death of a Naturalist marks the ...
3112,9780590032490,0590032496,The witches,Roald Dahl,Juvenile Nonfiction,http://books.google.com/books/content?id=tpQxo...,"A young boy and his Norwegian grandmother, who...",1997.0,4.17,208.0,254867.0,The witches,9780590032490 A young boy and his Norwegian gr...
3116,9780590227162,0590227165,How Much is that Guinea Pig in the Window?,Joanne Rocklin,Contests,http://books.google.com/books/content?id=DH5UG...,"Mr. Day's fourth-grade class has a contest, re...",1995.0,4.12,48.0,24.0,How Much is that Guinea Pig in the Window?,9780590227162 Mr. Day's fourth-grade class has...
3135,9780590876124,0590876120,The Littles and Their Amazing New Friend,John Peterson,Juvenile Fiction,http://books.google.com/books/content?id=3uy8G...,"On a hill above the Big Valley, the Littles ma...",1999.0,3.92,112.0,181.0,The Littles and Their Amazing New Friend,"9780590876124 On a hill above the Big Valley, ..."
3220,9780618711666,061871166X,The Hungry Tide,Amitav Ghosh,Fiction,http://books.google.com/books/content?id=LN16i...,"Presents a novel of life in modern India, chro...",2006.0,3.94,333.0,11220.0,The Hungry Tide,9780618711666 Presents a novel of life in mode...
3235,9780670036653,067003665X,The Roald Dahl Treasury,Roald Dahl,Juvenile Fiction,http://books.google.com/books/content?id=NJfZA...,Presents selections from the author's children...,2003.0,4.43,448.0,2091.0,The Roald Dahl Treasury,9780670036653 Presents selections from the aut...
3350,9780679406839,0679406832,Gift from the Sea,NaN,Biography & Autobiography,http://books.google.com/books/content?id=l8q6m...,"A woman's reflections on life, its stages, and...",1991.0,4.17,132.0,1314.0,Gift from the Sea,"9780679406839 A woman's reflections on life, i..."
3447,9780679882817,0679882812,Dr. Seuss's ABC,Dr. Seuss,Juvenile Fiction,http://books.google.com/books/content?id=mdn4W...,Pictures illustrate things that begin with eac...,1996.0,4.08,21.0,27135.0,Dr. Seuss's ABC: An Amazing Alphabet Book!,9780679882817 Pictures illustrate things that ...
3452,9780679891116,0679891110,The Cat in the Hat,Dr. Seuss,Juvenile Fiction,http://books.google.com/books/content?id=WocHz...,Two children sitting at home on a rainy day ar...,1997.0,4.16,61.0,290.0,The Cat in the Hat,9780679891116 Two children sitting at home on ...
3526,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,A Child's Garden of Verses,9780689823824 Here is a delightful look at chi...
3540,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,28261.0,"Moo, Baa, la la La!",9780689861130 Children will love joining in an...
3542,9780689863110,068986311X,The Eagle,Cynthia Rylant;Preston McDaniels,Juvenile Fiction,http://books.google.com/books/content?id=cxC9X...,Two mice that live in a lighthouse along with ...,2005.0,4.08,64.0,155.0,The Eagle,9780689863110 Two mice that live in a lighthou...
3785,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
3915,9780761316800,0761316809,It's Winter!,Linda Glaser,Juvenile Nonfiction,http://books.google.com/books/content?id=eSCmK...,A child observes the coming of winter and its ...,2002.0,3.63,32.0,80.0,It's Winter!,9780761316800 A child observes the coming of w...
3939,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,Judy Moody Saves the World!,9780763620875 When Judy Moody gets serious abo...
3940,9780763621643,0763621641,Castle Diary,Richard Platt;Chris Riddell,Juvenile Fiction,http://books.google.com/books/content?id=rFUBA...,As a page in his uncle's castle in thirteenth-...,2003.0,3.84,128.0,1072.0,Castle Diary: The Journal of Tobias Burgess,9780763621643 As a page in his uncle's castle ...
3954,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781 Titles in this series present ba...
4113,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
4114,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
4115,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
4116,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
4117,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
4126,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...
4130,9780786818723,0786818727,Baby Einstein: Violet's House,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=bC4HA...,"Violet, a very curious young mouse, invites ba...",2003.0,3.98,10.0,39.0,Baby Einstein: Violet's House: A Giant Touch-a...,"9780786818723 Violet, a very curious young mou..."
4131,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,"Baby Einstein: Water, Water Everywhere",9780786819119 Charming illustrations and playf...
4168,9780789422132,0789422131,Flowers,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=1DsEA...,Describes the physical characteristics and lif...,1997.0,4.00,64.0,8.0,Flowers,9780789422132 Describes the physical character...
4169,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,Tree,9780789458209 Photographs and text explore the...
4170,9780789493934,0789493934,Reptiles and Amphibians,Mark O'Shea;Tim Halliday,Juvenile Nonfiction,http://books.google.com/books/content?id=YdnZA...,Collects annotated photographs and description...,2002.0,3.99,256.0,51.0,Reptiles and Amphibians,9780789493934 Collects annotated photographs a...
4698,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...
4768,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,218.0,Providence of a Sparrow: Lessons from a Life G...,9781400033850 Describes the influence of a fou...
4797,9781400051571,1400051576,The Last Hours of Ancient Sunlight,Thom Hartmann,Political Science,http://books.google.com/books/content?id=7d4VD...,A revised edition of a landmark study offers a...,2004.0,4.22,400.0,1341.0,The Last Hours of Ancient Sunlight: The Fate o...,9781400051571 A revised edition of a landmark ...