In [13]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [14]:
from dotenv import load_dotenv
load_dotenv()

True

In [15]:
import pandas as pd

books = pd.read_csv("../data/books_cleaned.csv")

In [16]:
books

,isbn13,title,authors,categories,description,thumbnail,published_year,average_rating,num_pages,title_and_subtitle,tagged_description
0,9781804510407,Other Side of the Wire,Ralph J. Whitehead,"Germany. Heer;Germany. Heer. Reserve Corps, 14...","""By focusing on one of the principal German fo...",NaN,2022,NaN,NaN,Other Side of the Wire: Volume 2 - the Battle ...,"9781804510407 ""By focusing on one of the princ..."
1,9781108663229,African Literature and the CIA,Caroline Davis,Written communication;African literature;CIA;U...,"""During the period of decolonisation in Africa...",NaN,2020,NaN,NaN,African Literature and the CIA: Networks of Au...,"9781108663229 ""During the period of decolonisa..."
2,9780367418489,Interior Provocations,Anca I. Lasc;Pratt Institute Staff,Architecture;Interior architecture;Congresses;...,"""Interior Provocations: History, Theory, and P...",NaN,2020,NaN,NaN,Interior Provocations,"9780367418489 ""Interior Provocations: History,..."
3,9781800326514,An Unfortunate Christmas Murder,Hannah Hendy,English literature,"‘Tis the season for gold, frankincense and mur...",https://covers.openlibrary.org/b/id/15179740-L...,2022,NaN,NaN,An Unfortunate Christmas Murder,"9781800326514 ‘Tis the season for gold, franki..."
4,9781108485852,Legitimacy of Unseen Actors in International A...,Freya Baetens,Arbitration (international law);Jurisdiction (...,"""'Unseen actors' are vital to the functioning ...",NaN,2019,NaN,496.0,Legitimacy of Unseen Actors in International A...,"9781108485852 ""'Unseen actors' are vital to th..."
...,...,...,...,...,...,...,...,...,...,...,...
4995,9781952223174,"Why, As a Muslim, I Support Liberty",Mustafa Akyol,Religion;Philosophy;Liberty;Islam;Muslims;Reli...,"Islam, the second largest religion in the worl...",NaN,2021,NaN,192.0,"Why, As a Muslim, I Support Liberty","9781952223174 Islam, the second largest religi..."
4996,9781532147555,The Horror at Happy Landings,Robert Lawrence Stine;Kelly Matthews;Nichole M...,NaN,Two Martians unexpectedly land on Earth and ha...,https://covers.openlibrary.org/b/id/14408331-L...,2020,NaN,NaN,The Horror at Happy Landings: Just Beyond Volu...,9781532147555 Two Martians unexpectedly land o...
4997,9789004278783,The Blinded State,Mitko B. Panov,"Byzantine empire, history;Macedonia, history;H...","""This book is a revisionist account of Samuel'...",NaN,2019,NaN,478.0,The Blinded State,"9789004278783 ""This book is a revisionist acco..."
4998,9781784753474,Walls,Hollie Overton,"Abused women;Murder;Fiction;Fiction, suspense;...","""For fans of The Girl on the Train, The Walls ...",NaN,2018,NaN,416.0,Walls,"9781784753474 ""For fans of The Girl on the Tra..."
4999,9789188459381,Chase The Dream,Nathalie M L Römer,NaN,Every day is the same for Ella. She’s told by ...,https://covers.openlibrary.org/b/id/12542739-L...,2019,NaN,64.0,Chase The Dream,9789188459381 Every day is the same for Ella. ...

In [17]:
books["tagged_description"].to_csv("../data/tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

In [18]:
raw_documents = TextLoader("../data/tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0.1, chunk_overlap=0, separator="\n")
# chunk_size = 0.1 -- if this is more than one it may split on a chunk size rather than the separator
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 416, which is longer than the specified 0
Created a chunk of size 1035, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 951, which is longer than the specified 0
Created a chunk of size 1808, which is longer than the specified 0
Created a chunk of size 413, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1182, which is longer than the specified 0
Created a chunk of size 889, which is longer than the specified 0
Created a chunk of size 1745, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 983, which is longer than the specified 0
Created a chunk of size 619, which is longer than the specified 0
Created a chunk of size 1261, which is longer than the specified 0
Created a chunk of size 937, which is longer than the specified 0
Created a chunk of size 900, which is longer than the specified 0
Created a chunk of size 1455, which is longer than the specified 0
Created a chunk of size 844, which is longer than the specified 0
Created a chunk of size 995, which is longer than the specified 0
Created a chunk of size 877, which is longer than the specified 0
Created a chunk of size 1052, which is longer than the specified 0
Created a chunk of size 365, which is longer than the specified 0
Created a chunk of size 1078, which is longer than the specified 0
Created a chunk of size 212, which is longer than the specified 0
Created a chunk of size 1222, which is longer than the specified 0
Created a chunk of size 1630, which is longer than the specified 0
Created a chunk of size 660, which is longer than the specified 0
Created a chunk of size 424, which is longer than the specified 0
Created a chunk of size 1616, which is longer than the specified 0
Created a chunk of size 691, which is longer than the specified 0
Created a chunk of size 1909, which is longer than the specified 0
Created a chunk of size 1245, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 940, which is longer than the specified 0
Created a chunk of size 1288, which is longer than the specified 0
Created a chunk of size 1288, which is longer than the specified 0
Created a chunk of size 1452, which is longer than the specified 0
Created a chunk of size 2400, which is longer than the specified 0
Created a chunk of size 475, which is longer than the specified 0
Created a chunk of size 573, which is longer than the specified 0
Created a chunk of size 1232, which is longer than the specified 0
Created a chunk of size 1008, which is longer than the specified 0
Created a chunk of size 1254, which is longer than the specified 0
Created a chunk of size 347, which is longer than the specified 0
Created a chunk of size 1254, which is longer than the specified 0
Created a chunk of size 345, which is longer than the specified 0
Created a chunk of size 628, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 456, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 1665, which is longer than the specified 0
Created a chunk of size 178, which is longer than the specified 0
Created a chunk of size 1450, which is longer than the specified 0
Created a chunk of size 382, which is longer than the specified 0
Created a chunk of size 1251, which is longer than the specified 0
Created a chunk of size 1555, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 640, which is longer than the specified 0
Created a chunk of size 890, which is longer than the specified 0
Created a chunk of size 547, which is longer than the specified 0
Created a chunk of size 994, which is longer than the specified 0
Created a chunk of size 1162, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 1013, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 737, which is longer than the specified 0
Created a chunk of size 952, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 596, which is longer than the specified 0
Created a chunk of size 1377, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 492, which is longer than the specified 0
Created a chunk of size 1029, which is longer than the specified 0
Created a chunk of size 1306, which is longer than the specified 0
Created a chunk of size 1037, which is longer than the specified 0
Created a chunk of size 786, which is longer than the specified 0
Created a chunk of size 928, which is longer than the specified 0
Created a chunk of size 1463, which is longer than the specified 0
Created a chunk of size 485, which is longer than the specified 0
Created a chunk of size 475, which is longer than the specified 0
Created a chunk of size 672, which is longer than the specified 0
Created a chunk of size 954, which is longer than the specified 0
Created a chunk of size 1256, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 878, which is longer than the specified 0
Created a chunk of size 2470, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 240, which is longer than the specified 0
Created a chunk of size 924, which is longer than the specified 0
Created a chunk of size 1380, which is longer than the specified 0
Created a chunk of size 278, which is longer than the specified 0
Created a chunk of size 1866, which is longer than the specified 0
Created a chunk of size 927, which is longer than the specified 0
Created a chunk of size 952, which is longer than the specified 0
Created a chunk of size 251, which is longer than the specified 0
Created a chunk of size 613, which is longer than the specified 0
Created a chunk of size 2167, which is longer than the specified 0
Created a chunk of size 248, which is longer than the specified 0
Created a chunk of size 527, which is longer than the specified 0
Created a chunk of size 1519, which is longer than the specified 0
Created a chunk of size 899, which is longer than the specified 0
Created a chunk of size 866, which is longer than the specified 0
Created a chunk of size 765, which is longer than the specified 0
Created a chunk of size 791, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 552, which is longer than the specified 0
Created a chunk of size 1300, which is longer than the specified 0
Created a chunk of size 411, which is longer than the specified 0
Created a chunk of size 1561, which is longer than the specified 0
Created a chunk of size 2306, which is longer than the specified 0
Created a chunk of size 194, which is longer than the specified 0
Created a chunk of size 1202, which is longer than the specified 0
Created a chunk of size 3482, which is longer than the specified 0
Created a chunk of size 1104, which is longer than the specified 0
Created a chunk of size 770, which is longer than the specified 0
Created a chunk of size 552, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 1815, which is longer than the specified 0
Created a chunk of size 683, which is longer than the specified 0
Created a chunk of size 1551, which is longer than the specified 0
Created a chunk of size 547, which is longer than the specified 0
Created a chunk of size 1487, which is longer than the specified 0
Created a chunk of size 2389, which is longer than the specified 0
Created a chunk of size 153, which is longer than the specified 0
Created a chunk of size 1699, which is longer than the specified 0
Created a chunk of size 142, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1602, which is longer than the specified 0
Created a chunk of size 1145, which is longer than the specified 0
Created a chunk of size 1321, which is longer than the specified 0
Created a chunk of size 607, which is longer than the specified 0
Created a chunk of size 614, which is longer than the specified 0
Created a chunk of size 373, which is longer than the specified 0
Created a chunk of size 1437, which is longer than the specified 0
Created a chunk of size 910, which is longer than the specified 0
Created a chunk of size 1049, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 884, which is longer than the specified 0
Created a chunk of size 490, which is longer than the specified 0
Created a chunk of size 216, which is longer than the specified 0
Created a chunk of size 682, which is longer than the specified 0
Created a chunk of size 869, which is longer than the specified 0
Created a chunk of size 2891, which is longer than the specified 0
Created a chunk of size 1133, which is longer than the specified 0
Created a chunk of size 140, which is longer than the specified 0
Created a chunk of size 1572, which is longer than the specified 0
Created a chunk of size 676, which is longer than the specified 0
Created a chunk of size 1488, which is longer than the specified 0
Created a chunk of size 271, which is longer than the specified 0
Created a chunk of size 429, which is longer than the specified 0
Created a chunk of size 1494, which is longer than the specified 0
Created a chunk of size 659, which is longer than the specified 0
Created a chunk of size 1443, which is longer than the specified 0
Created a chunk of size 314, which is longer than the specified 0
Created a chunk of size 235, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 585, which is longer than the specified 0
Created a chunk of size 1099, which is longer than the specified 0
Created a chunk of size 1329, which is longer than the specified 0
Created a chunk of size 1467, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 560, which is longer than the specified 0
Created a chunk of size 319, which is longer than the specified 0
Created a chunk of size 1067, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 1060, which is longer than the specified 0
Created a chunk of size 313, which is longer than the specified 0
Created a chunk of size 1204, which is longer than the specified 0
Created a chunk of size 489, which is longer than the specified 0
Created a chunk of size 363, which is longer than the specified 0
Created a chunk of size 1446, which is longer than the specified 0
Created a chunk of size 171, which is longer than the specified 0
Created a chunk of size 417, which is longer than the specified 0
Created a chunk of size 159, which is longer than the specified 0
Created a chunk of size 783, which is longer than the specified 0
Created a chunk of size 1226, which is longer than the specified 0
Created a chunk of size 629, which is longer than the specified 0
Created a chunk of size 938, which is longer than the specified 0
Created a chunk of size 907, which is longer than the specified 0
Created a chunk of size 1183, which is longer than the specified 0
Created a chunk of size 210, which is longer than the specified 0
Created a chunk of size 435, which is longer than the specified 0
Created a chunk of size 829, which is longer than the specified 0
Created a chunk of size 1482, which is longer than the specified 0
Created a chunk of size 1087, which is longer than the specified 0
Created a chunk of size 450, which is longer than the specified 0
Created a chunk of size 1797, which is longer than the specified 0
Created a chunk of size 536, which is longer than the specified 0
Created a chunk of size 1052, which is longer than the specified 0
Created a chunk of size 823, which is longer than the specified 0
Created a chunk of size 967, which is longer than the specified 0
Created a chunk of size 1250, which is longer than the specified 0
Created a chunk of size 855, which is longer than the specified 0
Created a chunk of size 1116, which is longer than the specified 0
Created a chunk of size 497, which is longer than the specified 0
Created a chunk of size 1657, which is longer than the specified 0
Created a chunk of size 1408, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 541, which is longer than the specified 0
Created a chunk of size 1386, which is longer than the specified 0
Created a chunk of size 1579, which is longer than the specified 0
Created a chunk of size 1380, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 2490, which is longer than the specified 0
Created a chunk of size 1390, which is longer than the specified 0
Created a chunk of size 345, which is longer than the specified 0
Created a chunk of size 264, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 906, which is longer than the specified 0
Created a chunk of size 1094, which is longer than the specified 0
Created a chunk of size 1416, which is longer than the specified 0
Created a chunk of size 1208, which is longer than the specified 0
Created a chunk of size 805, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 534, which is longer than the specified 0
Created a chunk of size 861, which is longer than the specified 0
Created a chunk of size 679, which is longer than the specified 0
Created a chunk of size 1591, which is longer than the specified 0
Created a chunk of size 2514, which is longer than the specified 0
Created a chunk of size 1282, which is longer than the specified 0
Created a chunk of size 1998, which is longer than the specified 0
Created a chunk of size 1413, which is longer than the specified 0
Created a chunk of size 796, which is longer than the specified 0
Created a chunk of size 1996, which is longer than the specified 0
Created a chunk of size 1643, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 225, which is longer than the specified 0
Created a chunk of size 1199, which is longer than the specified 0
Created a chunk of size 1790, which is longer than the specified 0
Created a chunk of size 149, which is longer than the specified 0
Created a chunk of size 1029, which is longer than the specified 0
Created a chunk of size 871, which is longer than the specified 0
Created a chunk of size 125, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 1004, which is longer than the specified 0
Created a chunk of size 1002, which is longer than the specified 0
Created a chunk of size 129, which is longer than the specified 0
Created a chunk of size 752, which is longer than the specified 0
Created a chunk of size 1565, which is longer than the specified 0
Created a chunk of size 1208, which is longer than the specified 0
Created a chunk of size 895, which is longer than the specified 0
Created a chunk of size 758, which is longer than the specified 0
Created a chunk of size 219, which is longer than the specified 0
Created a chunk of size 888, which is longer than the specified 0
Created a chunk of size 1246, which is longer than the specified 0
Created a chunk of size 557, which is longer than the specified 0
Created a chunk of size 1431, which is longer than the specified 0
Created a chunk of size 1806, which is longer than the specified 0
Created a chunk of size 440, which is longer than the specified 0
Created a chunk of size 1475, which is longer than the specified 0
Created a chunk of size 238, which is longer than the specified 0
Created a chunk of size 1870, which is longer than the specified 0
Created a chunk of size 2007, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 898, which is longer than the specified 0
Created a chunk of size 337, which is longer than the specified 0
Created a chunk of size 331, which is longer than the specified 0
Created a chunk of size 453, which is longer than the specified 0
Created a chunk of size 938, which is longer than the specified 0
Created a chunk of size 544, which is longer than the specified 0
Created a chunk of size 1485, which is longer than the specified 0
Created a chunk of size 1609, which is longer than the specified 0
Created a chunk of size 924, which is longer than the specified 0
Created a chunk of size 802, which is longer than the specified 0
Created a chunk of size 1114, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 908, which is longer than the specified 0
Created a chunk of size 453, which is longer than the specified 0
Created a chunk of size 850, which is longer than the specified 0
Created a chunk of size 553, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 961, which is longer than the specified 0
Created a chunk of size 1761, which is longer than the specified 0
Created a chunk of size 671, which is longer than the specified 0
Created a chunk of size 1128, which is longer than the specified 0
Created a chunk of size 1331, which is longer than the specified 0
Created a chunk of size 751, which is longer than the specified 0
Created a chunk of size 959, which is longer than the specified 0
Created a chunk of size 1142, which is longer than the specified 0
Created a chunk of size 357, which is longer than the specified 0
Created a chunk of size 1376, which is longer than the specified 0
Created a chunk of size 812, which is longer than the specified 0
Created a chunk of size 859, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 161, which is longer than the specified 0
Created a chunk of size 393, which is longer than the specified 0
Created a chunk of size 342, which is longer than the specified 0
Created a chunk of size 1285, which is longer than the specified 0
Created a chunk of size 499, which is longer than the specified 0
Created a chunk of size 2066, which is longer than the specified 0
Created a chunk of size 842, which is longer than the specified 0
Created a chunk of size 627, which is longer than the specified 0
Created a chunk of size 1385, which is longer than the specified 0
Created a chunk of size 1540, which is longer than the specified 0
Created a chunk of size 254, which is longer than the specified 0
Created a chunk of size 797, which is longer than the specified 0
Created a chunk of size 1494, which is longer than the specified 0

In [19]:
documents[0]

Document(metadata={'source': '../data/tagged_description.txt'}, page_content='"9781804510407 ""By focusing on one of the principal German formations involved in the Somme fighting, the author brings to life this little-known period, from the initial German advance on the Somme in September 1914 through the formation of the front that became so well known two years later. Covers the early fighting around villages such as Serre, Beaumont-Hamel, Thiepval, Ovillers, La Boisselle and Fricourt."')

In [20]:
db_books = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings())

In [21]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 3)
docs

[Document(id='88dc7115-79e4-4bf5-b60c-90fe39fb2906', metadata={'source': '../data/tagged_description.txt'}, page_content='9781426331565 Packed with colorful photographs of adorable animals braving the elements, this picture book for preschoolers introduces kids to the weather they experience every day, including rain, clouds, sunshine, snow, storms, and more.'),
 Document(id='c5e43c8c-9a22-472c-93f4-2b6209836a3f', metadata={'source': '../data/tagged_description.txt'}, page_content='9780593462034 In a village on the African plains, a little girl stalls bedtime by saying good night to various animals and objects.'),
 Document(id='14228400-fe9d-4d58-b350-8b9654af98d6', metadata={'source': '../data/tagged_description.txt'}, page_content='9781663961853 Who Grows Up Here? - Beautiful drawings and lyrical text take the reader from the tundra to the tropics to discover a whole new world of baby animals.')]

In [22]:
# get the full data of the top book from the query
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

Empty DataFrame
Columns: [isbn13, title, authors, categories, description, thumbnail, published_year, average_rating, num_pages, title_and_subtitle, tagged_description]
Index: []

In [23]:
def get_semantic_recommendation(query: str) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 30)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [27]:
get_semantic_recommendation("A book about a woman astronaut")

,isbn13,title,authors,categories,description,thumbnail,published_year,average_rating,num_pages,title_and_subtitle,tagged_description
830,9781328948939,Brightly burning,Alexa Donne,Orphans;Fiction;Artificial intelligence;Virus ...,Seventeen-year-old Stella Ainsley wants just o...,NaN,2018,NaN,394.0,Brightly burning,9781328948939 Seventeen-year-old Stella Ainsle...
953,9781338262513,Satellite space mission,AnnMarie Anderson,Juvenile fiction;Artificial satellites;Explora...,Space Camp is the launching pad to becoming an...,NaN,2018,NaN,91.0,Satellite space mission,9781338262513 Space Camp is the launching pad ...
1462,9781421596976,Astra lost in space,篠原 健太,Space ships;Exploration;Astronauts;Planets;Int...,"After crashing on planet Icriss, all seems los...",NaN,2018,NaN,NaN,Astra lost in space: Revelation,"9781421596976 After crashing on planet Icriss,..."
2365,9781446432402,Beegu,Alexis Deacon,Extraterrestrial beings;Fiction;Children's fic...,A small creature from space finds no welcome o...,NaN,2018,NaN,NaN,Beegu,9781446432402 A small creature from space find...
2639,9798227464255,The Antarctica Conspiracy,"Henry, Lisa",Series:Time-to-Orbit-Unknown;Science Fiction;M...,"It hasn't been easy, but under the careful han...",https://covers.openlibrary.org/b/id/15128146-L...,2024,NaN,716.0,The Antarctica Conspiracy,"9798227464255 It hasn't been easy, but under t..."
3233,9780262539944,The Curie Society,Heather Einhorn;Adam Staffaroni;Janet Harvey;J...,"Secret societies;Comic books, strips;Women;Soc...","""An action-adventure original graphic novel, f...",https://covers.openlibrary.org/b/id/10874209-L...,2021,NaN,168.0,The Curie Society,"9780262539944 ""An action-adventure original gr..."
3437,9781642595826,Eslanda Second Ed,Barbara Ransby,African American anthropologists;Biography;Wom...,Chronicles the eventful life of the anthropolo...,NaN,2022,NaN,422.0,Eslanda Second Ed: The Large and Unconventiona...,9781642595826 Chronicles the eventful life of ...
4239,9780356521435,Revenant-X,David Wellington,horror;Science fiction;Sci Fi;Outer Space,"""The crew of the Artemis - led by Firewatch ag...",https://covers.openlibrary.org/b/id/14833503-L...,2024,NaN,500.0,Revenant-X,"9780356521435 ""The crew of the Artemis - led b..."
4500,9780316307598,Robot rescue,Drew Brockington,Juvenile fiction;Graphic novels;Robots;Astrona...,When Cat-Stro-Bot gets into trouble while help...,https://covers.openlibrary.org/b/id/8996789-L.jpg,2018,NaN,NaN,Robot rescue,9780316307598 When Cat-Stro-Bot gets into trou...
4546,9781465477132,Universe,Giles Sparrow,Juvenile literature;Galaxies;Cosmology;Cosmolo...,"Children will find out about the universe, our...",NaN,2018,NaN,64.0,Universe,9781465477132 Children will find out about the...
4869,9780756415426,To Each This World,Julie E. Czerneda,Human-alien encounters;Fiction,Biologist Julie E. Czerneda's new standalone s...,https://covers.openlibrary.org/b/id/14606694-L...,2022,NaN,468.0,To Each This World,9780756415426 Biologist Julie E. Czerneda's ne...